### PR TITLE
Fix b" output prefix

### LINKED ISSUE #107: runlike always prints `'b"` as prefix and `"` as suffix
https://github.com/lavie/runlike/commit/1d7e967965e68e26d2f1214ee6b7e4a0f76ca979 added an `.encode()` call, which turns the output string into a byte array.

But you need to use a different method for printing byte arrays to console: https://stackoverflow.com/a/3603160/5971497

### PR DESCRIPTION
**Pull request by reconman**
Fixes #107

### CODE REVIEW

**Comment by reconman** [comment]
Here's some output produced by runlike 1.4.5:
image

As you can see, it starts with `b"` because the .encode() method turns the output string into a byte array which is then printed to the console.

I removed the .encode() call and couldn't reproduce any UTF-8 encoding issues in Windows or Ubuntu.

The existing pytests used the string produced by `Inspector.format_cli()`, but since runlike.py converted the string before printing, I changed it to [click's CliRunner](https://click.palletsprojects.com/en/8.1.x/testing/) so the tests can check the actual console output.

File: fixtures.sh [hunk 1]
```diff
@@ -6,10 +6,14 @@ function sudocker() {
 
 sudocker build -t runlike_fixture dockerfiles/
 
+old_containers=$(sudocker ps -a --format '{{.Names}}' | grep runlike_fixture)
```
Comment (lavie) [inline fixtures.sh:9]: nice!

**Review by lavie — APPROVED** [review]
